Add brk2 erfpachtcanon to model
Amsterdam/GOB-Core pull request #761
Opened 2023-07-17 15:11 UTC by roel-devries

2023-07-19 11:57 UTC, peteradrichem requested changes

2023-07-19 11:57 UTC, peteradrichem commented on gobcore/model/gobmodel.json
> +        "version": "0.1",
Deze `version` wordt niet gebruikt. GOB kijkt alleen naar de `version` onder `schema`.

2023-07-20 07:53 UTC, roel-devries commented on gobcore/model/gobmodel.json
> +        "version": "0.1",
removed

2023-07-20 07:57 UTC, peteradrichem approved these changes

2023-07-20 08:22 UTC, merged